from tkinter import *

root = Tk()
root.title("Trabajo Práctico 15 de Marcos y Estilos con Tkinter")
#   Creación de marco
# marco = LabelFrame(root,text="Marco de Práctica 15",width=300,height=300)
# marco.pack(padx=25,pady=10)
# marco1 = LabelFrame(root,background="gold",width=200,height=400,border=0)
# marco2 = LabelFrame(root,background="gray62",width=200,height=400,border=0)
# marco1.grid(row=0,column=0)
# marco2.grid(row=0,column=1)
marco1 = LabelFrame(root,background="gold",width=50,height=50,border=0)
marco2 = LabelFrame(root,background="lime green",width=50,height=50,border=0)
marco3 = LabelFrame(root,background="gold",width=50,height=50,border=0)
marco4 = LabelFrame(root,background="lime green",width=50,height=50,border=0)
marco5 = LabelFrame(root,background="gold",width=50,height=50,border=0)
marco6 = LabelFrame(root,background="lime green",width=50,height=50,border=0)
marco7 = LabelFrame(root,background="gold",width=50,height=50,border=0)
marco8 = LabelFrame(root,background="lime green",width=50,height=50,border=0)
marco9 = LabelFrame(root,background="gold",width=50,height=50,border=0)
marco1.grid(row=0,column=0)
marco2.grid(row=0,column=1)
marco3.grid(row=0,column=2)
marco4.grid(row=1,column=0)
marco5.grid(row=1,column=1)
marco6.grid(row=1,column=2)
marco7.grid(row=2,column=0)
marco8.grid(row=2,column=1)
marco9.grid(row=2,column=2)


root.mainloop()